local Loc = Apollo.GetPackage("Gemini:Locale-1.0").tPackage:NewLocale("Interruptor", "enUS", true)
Loc["Never use alternatives!"] = true
Loc["Icons"] = true
Loc["Icon Distribution Value (0-255)"] = true
Loc["Interrupt Armor locked to Castbar"] = true
Loc["Big Icon"] = true
Loc["Hide default target castbar"] = true
Loc["Hide default focus castbar"] = true
Loc["Minimal Layout"] = true
Loc["Unlock Castbar"] = true
Loc["Lock Castbar"] = true
Loc["Reset Positioning"] = true
Loc["Interruptable"] = true
Loc["Uninterruptable"] = true
Loc["Highlighted"] = true
Loc["Intact"] = true
Loc["Destroyed (others)"] = true
Loc["Destroyed (me)"] = true
Loc["Reset"] = true
Loc["Focus"] = true
Loc["IA"] = true
Loc["Background Texture"] = true
Loc["Texture"] = true
Loc["Border Texture"] = true
Loc["Active Profile:"] = true
Loc["Border Size"] = true
Loc["Castbar"] = true
Loc["Interrupt Armor"] = true
Loc["Icon"] = true
Loc["Padding"] = true
Loc["Basis:"] = true
Loc["Border"] = true
Loc["Create"] = true
Loc["Background"] = true
Loc["Only in Combat"] = true
Loc["Friendly"] = true
Loc["Players"] = true
Loc["Targeting Priority"] = true
Loc["Target"] = true
Loc["MaxRank"] = "Highest Rank Creature"
Loc["Show Interrupt Armor only during cast"] = true
Loc["Gap"] = true
Loc["Keep Icon from previous cast"] = true
Loc["Vulnerable Bar Icon"] = true
Loc["No Icon"] = true
Loc["Dedicated Icon"] = true